language: python
python: 2.7
services:
  - memcached
  - redis-server
env:
  - TOX_ENV=py27-dj18-memcache
  - TOX_ENV=py27-dj19-memcache
  - TOX_ENV=py27-dj110-memcache
  - TOX_ENV=py34-dj18-memcache
  - TOX_ENV=py34-dj19-memcache
  - TOX_ENV=py34-dj110-memcache
  - TOX_ENV=py27-dj18-redis
  - TOX_ENV=py27-dj19-redis
  - TOX_ENV=py27-dj110-redis
  - TOX_ENV=py34-dj18-redis
  - TOX_ENV=py34-dj19-redis
  - TOX_ENV=py34-dj110-redis
install:
  - pip install tox coveralls codecov
script:
  - tox -e $TOX_ENV
after_success:
  - coveralls
  - codecov

matrix:
  allow_failures:
    - env: TOX_ENV=py27-dj110-memcache
    - env: TOX_ENV=py34-dj110-memcache
    - env: TOX_ENV=py27-dj110-redis
    - env: TOX_ENV=py34-dj110-redis

deploy:
  provider: pypi
  user: tim.messier
  password:
    secure: YDKe4d9BJEcH9Fm3328nTMTD1/oUDQfdlK6k53U2hloDFT8cA/YEqS2RjHAzgewjJnMNmCYMwVh/s0NFl/Ou2V/MAVS9zHXe1hyVO+TVnkDzHMB/I11Pf+7gexO1xbA6fevB+CzH/Ynx5VB9kyaQG5WP7IO7PcEKe47+ZPPULgU=
  distributions: sdist bdist_wheel
  on:
    tags: true
    branch: master
